sudo: required

language: cpp

dist: xenial

install:
  - sudo apt-get update
  - sudo apt-get install qtdeclarative5-dev qtbase5-dev-tools qt5-qmake
  

script:
  - export QT_SELECT=qt5
  - qmake BerlinVeganTests.pro
  - make
  - ./BerlinVeganTests
  - rm Makefile BerlinVeganTests *.o
